### ISSUE TITLE
Unknown browser query `last 1 version and not Explorer 10`

### ISSUE THREAD

**Issue by NegativeDearc** [pqina/vue-filepond#85]
I'm trying to use ```vue-filepond```just follow examples while encountered BrowserslistError as below

```
 error  in ./node_modules/filepond/dist/filepond.min.css

Module build failed: BrowserslistError: Unknown browser query `last 1 version and not Explorer 10`
```

Here's the package.json information. My Project generate by vue-cli@2

```
"dependencies": {
    "filepond": "^4.3.5",
    "filepond-plugin-file-validate-type": "^1.2.4",
    "filepond-plugin-image-preview": "^4.0.5",
    "material-design-icons-iconfont": "^4.0.5",
    "vue": "^2.6.10",
    "vue-filepond": "^5.1.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```
How to fix this?

**Comment by rikschennink** [comment]
Updating you're build script should solve this. The latest version of browserslist supports this query ( `last 1 version and not Explorer 10` ) but apparently not all packagers are up to date yet.

**Comment by NegativeDearc** [comment]
Yes, I tried to updated some packages
```
"postcss-import": "^12.0.1",
"postcss-loader": "^3.0.0",
"postcss-url": "^8.0.0"
``` 
then solved the problem.

Thanks

**Comment by flxwu** [comment]
I have got those exact same packages (& versions) but still face the same error :/

**Comment by rikschennink** [comment]
@flxwu There’s possibly another part of your build process that is not up to date

**Comment by PauloViniciusBaleeiro** [comment]
Hi @rikschennink , i got these problem, then I "solved"  importing css files by CDN. I´m using Vue version 2.5.21. Before this "solution" i tryed update the npm packages but I still getting errors.

**Comment by RoraxHan** [comment]
Is there any solution to solve this problem without using the cdn to import filepond.min.css?
I've updated all packages used in my project like webpack, webpack-cli, css-loader, postcss-*, etc.
Any suggestion will help me.

**Comment by rikschennink** [comment]
@RoraxHan Maybe this helps:
https://github.com/browserslist/browserslist/issues/323#issuecomment-442877204

**Comment by Oscarz90** [comment]
guys, Im facing the same issue, any recomendation, I followed the above solutions but the dont work

**Comment by srivastavarnav** [comment]
Guys, did anyone got this working? If yes, please suggest the steps to resolve. None of the above solutions worked for me

**Comment by bgshu** [comment]
Guys I found a solution that worked for me!  In angular.json I removed "./node_modules/filepond/dist/filepond.min.css" and it compiled successfully. Unfortunately it removes the styling of the filepond, but I'm currently tweaking around removing other styles because there's obviously some sort of styling conflict.

**Comment by injitools** [comment]
npm i -D autoprefixer@9
